include:
  - project: 'carpinion/ci/templates'
    file: 'vanilla-helm.yaml'

variables:
  CHART_REPOSITORY_URL: "${CHART_REPOSITORY_PRIVATE_URL}"
  CHART_SRC_DIR: ./src/helm

verify:
  when: delayed
  start_in: 5 minutes
