include:
  - project: 'carpinion/ci/templates'
    file: 'vanilla-helm.yaml'

stages:
  - build
  - publish
  - deploy
  - verify

publish-private:
  stage: publish
  tags:
    - aws
  except:
    - tags
  script:
    - curl -u publisher:MzQwMjY0NTk4ZDc0 --fail --data-binary "@dist/$NAME-$VERSION.tgz" $CHART_REPOSITORY_PRIVATE_URL

verify:
  stage: verify
  tags:
    - aws
  except:
    - tags
  environment:
    name: $CI_COMMIT_REF_NAME
  when:
    manual
  script:
    - helm test "$CI_ENVIRONMENT_SLUG"
