stages:
  - build
  - publish
  - deploy

default:
  image: docker-gitlab.touk.pl/carpinion/ci/k8s-tools
  before_script:
    - export VERSION=`helm show chart hermes | grep ^version | sed -e "s/.*:\ //;s/SNAPSHOT/SNAPSHOT.${CI_PIPELINE_IID}/"`

build:
  stage: build
  artifacts:
    expire_in: 1d
    paths:
      - ./dist/
  script:
    - helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
    - helm dependencies build hermes
    - helm package hermes -d dist --version $VERSION

publish:
  stage: publish
  only:
    - master
  script:
    - curl -u publisher:MzQwMjY0NTk4ZDc0 --fail --data-binary "@dist/hermes-$VERSION.tgz" https://chartmuseum.carpinion.touk.pl/public/api/charts

deploy:
  stage: deploy
  only:
    - master
  environment:
    name: $CI_COMMIT_REF_NAME
  script:
    - helm repo add touk https://chartmuseum.carpinion.touk.pl/public/
    - helm upgrade -i --devel "$CI_ENVIRONMENT_SLUG"  -f values.yaml touk/hermes
