include:
  - project: 'carpinion/ci/templates'
    file: 'vanilla-helm.yaml'

variables:
  CHART_REPOSITORY_AUTH: "${CHARTS_PUBLIC_AUTH}"

publish.release:
  variables:
    CHART_REPOSITORY_URL: ${CHARTS_PUBLIC_RELEASES_URL}

publish.snapshot:
  variables:
    CHART_REPOSITORY_URL: ${CHARTS_PUBLIC_SNAPSHOTS_URL}

deploy:
  variables:
    CHART_REPOSITORY_URL: ${CHARTS_PUBLIC_SNAPSHOTS_URL}
