stages:
  - build
  - publish

default:
  image: docker-gitlab.touk.pl/carpinion/ci/k8s-tools
  before_script:
    - export VERSION=`helm3 show chart hermes | grep ^version | sed -e "s/.*:\ //;s/SNAPSHOT/SNAPSHOT.${CI_PIPELINE_IID}/"`

build:
  stage: build
  artifacts:
    expire_in: 1d
    paths:
      - ./dist/
  script:
    # - |
    #   kubectl create secret -n "$KUBE_NAMESPACE" docker-registry gitlab-registry \
    #     --docker-server="$CI_REGISTRY" \
    #     --docker-username="${CI_DEPLOY_USER:-$CI_REGISTRY_USER}" \
    #     --docker-password="${CI_DEPLOY_PASSWORD:-$CI_REGISTRY_PASSWORD}" \
    #     --docker-email="$GITLAB_USER_EMAIL" \
    #     -o yaml --dry-run | kubectl replace -n "$KUBE_NAMESPACE" --force -f -
    - helm3 repo add stable https://kubernetes-charts.storage.googleapis.com/
    - helm3 repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
    - helm3 repo add riskfocus https://riskfocus.github.io/helm-charts-public/
    - helm3 dependencies build hermes
    - helm3 package hermes -d dist --version $VERSION

publish:
  stage: publish
  script:
    - curl -u publisher:MzQwMjY0NTk4ZDc0 --fail --data-binary "@dist/hermes-$VERSION.tgz" https://chartmuseum.carpinion.touk.pl/public/api/charts
