deploy:
  image: docker-gitlab.touk.pl/carpinion/ci/k8s-tools
  environment:
    name: $CI_COMMIT_REF_NAME # it means branch or tag name
  script:
    - |
      kubectl create secret -n "$KUBE_NAMESPACE" docker-registry gitlab-registry \
        --docker-server="$CI_REGISTRY" \
        --docker-username="${CI_DEPLOY_USER:-$CI_REGISTRY_USER}" \
        --docker-password="${CI_DEPLOY_PASSWORD:-$CI_REGISTRY_PASSWORD}" \
        --docker-email="$GITLAB_USER_EMAIL" \
        -o yaml --dry-run | kubectl replace -n "$KUBE_NAMESPACE" --force -f -
    - helm3 repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
    - helm3 dependencies build hermes
    - helm3 upgrade -i --devel "$CI_ENVIRONMENT_SLUG" --set kafka.url="master-kafka.nk-cloud-1251-master.k8s-carpinion.touk.pl:9092",kafka.zookeeperUrl="master-zookeeper.nk-cloud-1251-master.k8s-carpinion.touk.pl:2181" hermes
