kafka:
  namespace: "{{ .Release.Name }}"
  replicas: 1
  zookeeper:
    replicaCount: 1

management:
  image:
    pullPolicy: Always
  ingress:
    enabled: false
  cors:
    allowed-origin: https://hermes.cloud.nussknacker.io
frontend:
  image:
    pullPolicy: Always
  ingress:
    enabled: false
consumers:
  image:
    pullPolicy: Always
