kafka:
  namespace: "{{ .Release.Name }}"
  replicas: 1
  zookeeper:
    replicaCount: 1
    logLevel: INFO

management:
  image:
    pullPolicy: Always
  ingress:
    enabled: true
    skipHost: true
  topic:
    partitions: 1
    avroContentTypeMetadataRequired: false
  console:
    topic:
      avroContentTypeMetadataRequired: false
frontend:
  image:
    pullPolicy: Always
  ingress:
    enabled: false
  additionalConfig: 
    test1: value1
  secretConfig:  
    test2: value2
consumers:
  image:
    pullPolicy: Always
