kafka:
  namespace: "{{ .Release.Name }}"
  replicas: 1
  zookeeper:
    replicaCount: 1

management:
  image:
    pullPolicy: Always
  ingress:
    enabled: true
    annotations:
      certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    domain: carpinion.touk.pl
frontend:
  image:
    pullPolicy: Always
  ingress:
    enabled: false
consumers:
  image:
    pullPolicy: Always
