kafka:
  namespace: "{{ .Release.Name }}"
  replicas: 1
  zookeeper:
    replicaCount: 1
    logLevel: INFO

management:
  image:
    pullPolicy: Always
  ingress:
    enabled: true
    skipHost: true
  topic:
    partitions: 1
    avroContentTypeMetadataRequired: false
  console:
    topic:
      avroContentTypeMetadataRequired: false
  additionalConfig: 
    management-test1: value1
    management-test1a: value1a
  secretConfig:  
    management-test2: value2
    management-test2a: value2a
frontend:
  image:
    pullPolicy: Always
  ingress:
    enabled: false
  additionalConfig: 
    frontend-test1: value1
    frontend-test1a: value1a
  secretConfig:  
    frontend-test2: value2
    frontend-test2a: value2a
consumers:
  image:
    pullPolicy: Always
  additionalConfig: 
    consumers-test1: value1
    consumers-test1a: value1a
  secretConfig:  
    consumers-test2: value2
    consumers-test2a: value2a
