kafka:
  namespace: "{{ .Release.Name }}"
  replicas: 1
  zookeeper:
    replicaCount: 1
    logLevel: INFO

management:
  image:
    pullPolicy: Always
  ingress:
    enabled: true
    domain: carpinion.touk.pl
  topic:
    partitions: 1  
  cors:
    allowed-origin: "https://{{ .Release.Name }}.hermes.cloud.nussknacker.io"
frontend:
  image:
    pullPolicy: Always
  ingress:
    enabled: false
consumers:
  image:
    pullPolicy: Always
