kafka:
  namespace: "{{ .Release.Name }}"
  replicas: 1
  zookeeper:
    replicaCount: 1

management:
  image:
    pullPolicy: Always
  ingress:
    enabled: true
    domain: carpinion.touk.pl
  cors:
    allowed-origin: "https://{{ .Release.Name }}.hermes.cloud.nussknacker.io"
frontend:
  image:
    pullPolicy: Always
  ingress:
    enabled: false
consumers:
  image:
    pullPolicy: Always
