kafka:
  enabled: true
  namespace: "hermes"
  replicas: 1
  zookeeper:
    replicaCount: 1
management:
  ingress:
    enabled: false
frontend:
  ingress:
    enabled: false
schema-registry:
  enabled: true
