apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes.consumers.fullname" . }}-secret
data: 
  consumers-secret.yaml: |-
  {{ .Values.consumers.secretConfig | toYaml | b64enc | indent 4}}
{{ range $key, $value := .Values.consumers.additionalSecretFiles }}
  {{ $key | nindent 2}}: {{ $value }}
{{- end }}