apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hermes.consumers.fullname" . }}
  labels:
    {{- include "hermes.consumers.labels" . | nindent 4 }}
data:
  consumers.yaml: |-
    consumer:
      zookeeper:
        clusters:
          - datacenter: "dc"
            root: {{ include "hermes.zookeeperRoot" .  | quote }}
            connectionString: {{ include "hermes.zookeeperConnectString" . | quote }}
            connectionTimeout: 5000
            sessionTimeout: 7000
      kafka:
        clusters:
          - datacenter: "dc"
            brokerList: {{ include "hermes.kafkaBootstrapServers" . | quote }}
    {{- if .Values.kafkaNamespace }}
        namespace: {{ tpl .Values.kafkaNamespace . }}
    {{- end }}       
      schema:
        repository:
          serverUrl: {{ include "hermes.schemaRegistryUrl" . | quote }}
          subjectSuffixEnabled: true
          subjectNamespaceEnabled: true
      metrics:
        graphiteReporterEnabled: false
      workload:
        consumersPerSubscription:1
    {{- with .Values.consumers.additionalConfig }}
    {{ tpl (toYaml . | nindent 4) $ }}
    {{- end }}
  {{- if .Values.consumers.logbackConfig }}
  logback.xml: {{ toYaml .Values.consumers.logbackConfig | indent 2 }}
  {{- else }}
  logback.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration scan="true" scanPeriod="5 seconds">

        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
                <Pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n</Pattern>
            </encoder>
        </appender>

        <logger name="org.apache.zookeeper" level="ERROR" />
        <logger name="kafka" level="WARN"/>

        <root level="INFO">
            <appender-ref ref="STDOUT" />
        </root>

    </configuration>
  {{- end }}
  
