apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes.consumers.fullname" . }}-secret
data: 
  consumers-secret.properties: |-
  {{ include "print.secrets" .Values.consumers | b64enc | indent 2}}
{{ range $key, $value := .Values.consumers.additionalSecretFiles }}
  {{ $key | nindent 2}}: {{ $value | b64enc }}
{{- end }}