apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes.frontend.fullname" . }}-secret
data: 
  frontend-secret.properties: |-
  {{ include "print.secrets" .Values.frontend | b64enc | indent 2}}
{{ range $key, $value := .Values.frontend.additionalSecretFiles }}
  {{ $key | nindent 2}}: {{ $value | b64enc }}
{{- end }}