apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hermes.frontend.fullname" . }}
  labels:
    {{- include "hermes.frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "hermes.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/frontend-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "hermes.frontend.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "hermes.frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ template "hermes.name" . }}-{{ .Values.frontend.name }}
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ default ( print "hermes-" .Chart.AppVersion ) .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /etc/hermes
            - name: storage
              mountPath: /opt/frontend/storage
          envFrom:
            - configMapRef:
                optional: true
                name: {{ default (printf "%s-env" (include "hermes.frontend.fullname" . )) .Values.envConfigMapOverride }}
          env:
            - name: HERMES_FRONTEND_OPTS
              value: -Darchaius.configurationSource.additionalUrls=file:///etc/hermes/frontend.properties,file:///etc/hermes/frontend-secret.properties -Dlogback.configurationFile=/etc/hermes/logback.xml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.frontend.livenessProbe.failureThreshold }}
          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: {{ .Values.frontend.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.frontend.startupProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      volumes:
        - name: config
          projected: 
            sources:
            - configMap:
                name: {{ include "hermes.frontend.fullname" . }}
            - secret:
                name: {{ include "hermes.frontend.fullname" . }}-secret
        - name: storage
          hostPath:
            path: "/opt/frontend/storage"
      {{- with .Values.management.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
