apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes.frontend.fullname" . }}-secret
data: 
  frontend-secret.properties: |-
{{ range $key, $value := .Values.frontend.secretConfig }}
  {{- printf "%s=%s" $key $value | b64enc | indent 4}}
{{- end -}}    
