{{- if .Values.frontend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hermes.frontend.serviceAccountName" . }}
  labels:
    {{- include "hermes.frontend.labels" . | nindent 4 }}
{{- end -}}
