apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes.management.fullname" . }}-secret
data: 
  management-secret.yaml: |-
  {{ .Values.management.secretConfig | toYaml | b64enc | indent 4}}
{{ range $key, $value := .Values.management.additionalSecretFiles }}
  {{ $key | nindent 2}}: {{ $value }}
{{- end }}