apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hermes.management.fullname" . }}
  labels:
    {{- include "hermes.management.labels" . | nindent 4 }}
data:
  management.yaml: |-
    application:
      name: hermes-management

    topic:
      replicationFactor: 1
      defaultSchemaIdAwareSerializationEnabled: true

    zookeeper:
      enabled: false

    storage:
      pathPrefix: {{ include "hermes.zookeeperRoot" . }}
      clusters:
        -
          datacenter: dc
          clusterName: zk
          connectionString: {{ include "hermes.zookeeperConnectString" . }}

    kafka:
    {{- if .Values.kafkaNamespace }}
      defaultNamespace: {{ tpl .Values.kafkaNamespace . }}
    {{- end }}
      clusters:
        -
          datacenter: dc
          clusterName: primary
          connectionString: {{ include "hermes.zookeeperConnectString" . }}
          connectionTimeout: 5000
          bootstrapKafkaServer: {{ include "hermes.kafkaBootstrapServers" . }}

    metrics:
      graphiteHttpUri: graphite:8082
      graphite:
        enabled: true

    server:
      port: {{ .Values.management.service.port }}

    spring:
      jersey:
        type: filter

    management:
      endpoints:
        web:
          base-path: /
      rest-template:
        connect-timeout: 10000
        read-timeout: 10000
      server:
        servlet:
          context-path: /
      health:
        periodSeconds: 30
        enabled: true
      consumer-groups:
        create-manually: true

    audit.enabled: false

    topicOwnerCache:
      refreshRateInSeconds: 300 # 5 minutes

    subscriptionOwnerCache:
      refreshRateInSeconds: 300

    schema:
      repository:
        type: schema_registry
        serverUrl: {{ include "hermes.schemaRegistryUrl" . }}
        subjectSuffixEnabled: true
        subjectNamespaceEnabled: true
        validationEnabled: true

    console:
      configurationLocation: console/config-local.json
      configurationType: classpath_resource

    {{- with .Values.management.cors }}
    cors: {{ tpl (toJson .) $ }}
    {{- end }}
