apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes.management.fullname" . }}-secret
data: 
  management-secret.yaml: |-
  {{ .Values.management.secretConfig | toYaml | b64enc | indent 4}}
  client.truststore.jks: {{ .Values.management.trustore }}
{{ range $key, $value := .Values.management.additionalSecretFiles }}
  {{ $key | nindent 2}}: {{ $value | b64enc }}
{{- end }}