apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hermes.management.fullname" . }}
  labels:
    {{- include "hermes.management.labels" . | nindent 4 }}
data:
  management.yaml: |-
    server:
      port: {{ .Values.management.service.port }}

    application:
      name: hermes-management


    kafka:
    {{- if .Values.kafka.namespace }}
      defaultNamespace: {{ .Values.kafka.namespace }}
    {{- end }}
      clusters:
        -
          datacenter: dc
          clusterName: primary
          connectionString: {{ include "hermes.zookeeperUrl" . }}
          connectionTimeout: 3000
          bootstrapKafkaServer: {{ include "hermes.kafkaUrl" . }}
    
    storage:
      pathPrefix: {{ include "hermes.zookeeperRoot" . }}
      clusters:
        -
          datacenter: dc
          clusterName: zk
          connectionString: {{ include "hermes.zookeeperUrl" . }}

    topic:
      replicationFactor: 1

    metrics:
      graphite:
        host: graphite
      graphiteHttpUri: http://localhost:80
      enabled: false

    schema:
      repository:
        serverUrl: {{ include "hermes.schemaRegistryUrl" . }}

  
