apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hermes.management.fullname" . }}
  labels:
    {{- include "hermes.management.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.management.replicaCount }}
  selector:
    matchLabels:
      {{- include "hermes.management.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/management-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "hermes.management.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "hermes.management.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.management.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ template "hermes.name" . }}-{{ .Values.management.name }}
          securityContext:
            {{- toYaml .Values.management.securityContext | nindent 12 }}
          image: "{{ .Values.management.image.repository }}:{{ default ( print "hermes-" .Chart.AppVersion ) .Values.management.image.tag }}"
          imagePullPolicy: {{ .Values.management.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /etc/hermes
          env:
            - name: SERVER_USE_FORWARD_HEADERS
              value: "true"
            - name: SPRING_CONFIG_LOCATION
              value: "file:///etc/hermes/management.yaml,file:///etc/hermes/management-secret.yaml"  
          envFrom:
            - configMapRef:
                optional: true
                name: {{ default (printf "%s-env" (include "hermes.management.fullname" . )) .Values.envConfigMapOverride }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
{{/*      we are using tcp probes to handle both secured and public apis    */}}
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: {{ .Values.management.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.management.livenessProbe.failureThreshold }}
          startupProbe:
            tcpSocket:
              port: http
            periodSeconds: {{ .Values.management.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.management.startupProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.management.resources | nindent 12 }}
      volumes:
        - name: config
          projected: 
            sources:
            - configMap:
                name: {{ include "hermes.management.fullname" . }}
            - secret:
                name: {{ include "hermes.management.fullname" . }}-secret
      {{- with .Values.management.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.management.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.management.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
