{{- if .Values.consumers.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hermes.consumers.serviceAccountName" . }}
  labels:
    {{- include "hermes.consumers.labels" . | nindent 4 }}
{{- end -}}
