{{- if and .Values.consumers.persistence.enabled (not .Values.consumers.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "hermes.consumers.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.consumers.persistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "hermes.consumers.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.consumers.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.consumers.persistence.size | quote }}
{{- if .Values.consumers.persistence.storageClass }}
{{- if (eq "-" .Values.consumers.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.consumers.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
