apiVersion: v1
kind: Service
metadata:
  name: {{ include "hermes.consumers.fullname" . }}
  labels:
    {{- include "hermes.consumers.labels" . | nindent 4}}
spec:
  type: {{ .Values.consumers.service.type }}
  ports:
    - port: {{ .Values.consumers.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hermes.consumers.selectorLabels" . | nindent 4 }}