apiVersion: v1
kind: Service
metadata:
  name: {{ include "hermes.frontend.fullname" . }}
  labels:
    {{- include "hermes.frontend.labels" . | nindent 4}}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hermes.frontend.selectorLabels" . | nindent 4 }}