apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hermes.frontend.fullname" . }}
  labels:
    {{- include "hermes.frontend.labels" . | nindent 4 }}
data:
  frontend.properties: |-
    zookeeper.connect.string={{ include "hermes.zkUrl" . }}
    zookeeper.root=/hermes

    kafka.broker.list={{ include "hermes.kafkaUrl" . }}
    kafka.zookeeper.connect.string={{ include "hermes.zkUrl" . }}

    kafka.topic.partitions=4
    kafka.topic.replication.factor=1

    metrics.graphite.reporter=false
  logback.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>

        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
                <Pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n</Pattern>
            </encoder>
        </appender>

        <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>/opt/consumers/storage/hermes-frontend.log</file>
            <encoder>
                <Pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n</Pattern>
            </encoder>
            <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                <maxHistory>1</maxHistory>
                <fileNamePattern>hermes-frontend-%d{yyyy-MM-dd}.log</fileNamePattern>
            </rollingPolicy>
        </appender>

        <logger name="org.apache.zookeeper" level="ERROR" />

        <!--Selector spams ERROR level messages every 100ms on IOException-->
        <logger name="org.apache.kafka.common.network.Selector" level="OFF"/>

        <logger name="kafka" level="WARN"/>

        <root level="INFO">
            <appender-ref ref="STDOUT" />
            <appender-ref ref="FILE" />
        </root>

    </configuration>

  
  