{{- if .Values.management.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hermes.management.serviceAccountName" . }}
  labels:
    {{- include "hermes.management.labels" . | nindent 4 }}
{{- end -}}
