apiVersion: v2
name: hermes
description: A Helm chart for Kubernetes of Hermes, a reliable and easy to use message broker built on top of Kafka.
home: https://hermes.allegro.tech/
icon: https://hermes.allegro.tech/img/hermes.png
keywords:
  - kafka
  - hermes
  - allegro
type: application
version: 0.3.1-SNAPSHOT
appVersion: 1.5.2
sources:
  - https://github.com/allegro/hermes
maintainers:
  - name: TouK
    email: helm-charts@touk.pl
    url: https://touk.pl/

dependencies:
  - name: kafka
    version: ^0.21.2
    repository: "@incubator"
    condition: kafka.enabled
  - name: schema-registry
    version: ^1.1.9
    repository: "@incubator"
    condition: schema-registry.enabled
