apiVersion: v2
name: hermes
description: A Helm chart for Kubernetes of Hermes, a reliable and easy to use message broker built on top of Kafka.
home: https://hermes.allegro.tech/
icon: https://hermes.allegro.tech/img/hermes.png
keywords:
  - kafka
  - hermes
  - allegro
type: application
version: 0.5.14-SNAPSHOT
appVersion: 1.12.3
sources:
  - https://github.com/allegro/hermes
maintainers:
  - name: TouK
    email: helm-charts@touk.pl
    url: https://touk.pl/

dependencies:
  - name: kafka
    version: 20.0.2
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: apicurio-registry
    version: 0.1.3
    repository: https://helm-charts.touk.pl/public/
    condition: apicurio-registry.enabled
